### ISSUE TITLE
Add PHP7.4 support

### ISSUE THREAD

**Issue by Ghostscypher** [somnambulist-tech/validation#4]
Hello, is it possible for PHP7.4 support to be added... it's an awesome library, and i have a legacy code which still uses php7.4 and i'd really love if we had a 7.4 support

**Comment by dave-redfern** [comment]
@Ghostscypher unfortunately I would have to remove all promoted properties, scalar type hints, and any other PHP8 features. Basically it would be a separate major branch and that's beyond my capacity to be able to support.

You are welcome to fork and patch as a 7.4 version.
